#!/usr/bin/env python3
"""preflight.py — one-command wake/pre-push preflight wrapper (stdlib only).

Runs the whole preflight ritual in sequence and reports one PASS/FAIL line per
check, exiting with the WORST (max) exit code so a single red check reds the run:

- `check_sections.py`          — partition: sections ↔ fleet-manifest active lanes.
- `check_ideas.py`             — contents: every idea file parses per the README grammar.
- `check_ideas.py --outbox`    — integrity: outbox proposals ↔ sim-ready ideas.
- `bootstrap.py check --strict --status-only` — control gate: the status heartbeat.
- `preflight.py --gate-wiring` — self-check: the substrate-gate workflow still runs
  this wrapper in its non-control lane (the KIT-OWNED gate file is regenerated by
  every `bootstrap upgrade`, which drops the PR #18 step — happened live in PR #35).
- `preflight.py --open-work`   — ADVISORY ONLY, always exit 0: lists open remote
  branches besides main (`git ls-remote --heads origin`) and uncommitted local state
  (`git status --porcelain`) so a wake/pre-push sees in-flight sibling work BEFORE a
  collision (PRs #38/#39/#40 all leaned on a remembered ad-hoc `ls-remote`). Findings
  are information, never failure — a network blip must not red a PR that changed
  nothing, so this check contributes exit 0 unconditionally and CI stays hermetic.
- `preflight.py --branch-prefix-drift` — ADVISORY ONLY, always exit 0: derives the
  repo's real merged-branch prefixes from local `git log --merges` subjects and warns
  when a RECURRING prefix (>=2 merged branches) matches no
  `substrate.config.json::automerge.branch_patterns` entry — the silent-no-op class
  PR #55 fixed by survey (the kit's default `claude/*` matched zero real branches, so
  the staged auto-merge enabler was disarmed for a whole slice with nothing red
  anywhere). Branch names come from TWO local sources: PR-merge subjects, plus
  `Head-ref: <branch>` provenance lines the auto-merge enabler stamps into squash
  commit bodies (squash subjects carry no branch name — the PR #62 card's 💡; the
  subject leg stays the fallback for pre-provenance history). Local git only
  (hermetic); a shallow clone or provenance-less squash history degrades to an
  informational line, still exit 0.
- `preflight.py --step-anchor-drift` — ADVISORY ONLY, always exit 0: the PR #36
  card's 💡 — the gate-wiring self-check matches its anchors as BYTE strings, so
  a deliberate gate-step rewording that forgets to co-edit the
  `PREFLIGHT_RUN`/`NON_CONTROL_GUARD` constants drifts silently in two ways: a
  reworded run line makes the byte check FALSE-red on the next regen (annoying,
  safe), and a rewrite that keeps both byte-needles while moving the guard OFF
  the step's actual `if:` line could FALSE-green (the guard-semantics-dropped
  class). This advisory stem-scans the gate for preflight-run-like lines and
  warns when one exists that does not byte-match the anchor, or when the anchored
  run line's own step carries the guard bytes anywhere but its `if:` condition.
- `preflight.py --heartbeat-keys` — ADVISORY ONLY, always exit 0: the PR #59
  card's 💡 — undeclared heartbeat extension keys should surface at WRITE time,
  not at a consumer's parser (the leak class is only ever measured one key
  behind: `mode:`/`BACKPRESSURE:` measured by websites' parser, `routine:`
  caught only at round-4's first live enforcement). Parses each declared
  heartbeat file's top-level `<key>:` tokens and warns on any key outside the
  control/README format block's documented set (fold session-local signals into
  `notes:` or `phase:`, per the round-4 fold-in-over-declare decision). Hermetic:
  one local file, one local grammar set.
- `preflight.py --enabler-anchors` — ADVISORY ONLY, always exit 0: asserts BOTH
  host customizations survive in the KIT-OWNED auto-merge enabler (the PR #86
  card-status guard in the arm step's `if`, and the PR #62-lineage `Head-ref:`
  `--body` squash provenance on the arm command). Every adopt/upgrade regenerates
  the enabler and drops both; the kit's carve-out scan is STEP-granular and blind
  to the in-step `--body` edit (proven live on the v1.9.0 upgrade — manual diff
  was the only catch). Report-only on first landing (observe before block — the
  v1.10.0-hop card records the promotion condition).

Convention source: control/README.md § Per-session ritual + README § Landing
conventions — this collects the (previously discipline-only) multi-command ritual
into one command; each check stays independently runnable. Report-only: it never
edits files. Origin: PR #2 session card 💡 (wake-preflight wiring).

Usage:
    python3 scripts/preflight.py

Exit codes: worst child exit — 0 = all green · 1 = violations · 2 = a check could
not run (missing input / unparseable manifest / crashed child, reported as 2).
"""

from __future__ import annotations

import fnmatch
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PY = sys.executable or "python3"

# The ritual, in order — ONE edit here per new preflight check (keep in sync with
# control/README.md § Per-session ritual, loudly: a check missing here silently
# falls back to session discipline).
CHECKS: list[tuple[str, list[str]]] = [
    ("check_sections", [PY, "scripts/check_sections.py"]),
    ("check_ideas", [PY, "scripts/check_ideas.py"]),
    ("check_ideas --outbox", [PY, "scripts/check_ideas.py", "--outbox"]),
    ("bootstrap check --strict --status-only",
     [PY, "bootstrap.py", "check", "--strict", "--status-only"]),
    ("gate-wiring self-check",
     [PY, "scripts/preflight.py", "--gate-wiring"]),
    ("open-work advisory (report-only, never gates)",
     [PY, "scripts/preflight.py", "--open-work"]),
    ("branch-prefix-drift advisory (report-only, never gates)",
     [PY, "scripts/preflight.py", "--branch-prefix-drift"]),
    ("enabler-anchors advisory (report-only, never gates)",
     [PY, "scripts/preflight.py", "--enabler-anchors"]),
    ("step-anchor-drift advisory (report-only, never gates)",
     [PY, "scripts/preflight.py", "--step-anchor-drift"]),
    ("heartbeat-keys advisory (report-only, never gates)",
     [PY, "scripts/preflight.py", "--heartbeat-keys"]),
]

GATE_FILE = ".github/workflows/substrate-gate.yml"
PREFLIGHT_RUN = "run: python3 scripts/preflight.py"
NON_CONTROL_GUARD = "steps.lane.outputs.control_only != 'true'"


def check_gate_wiring() -> int:
    """Assert the gate↔ritual convergence step (PR #18) is still wired.

    The gate file is KIT-OWNED — every `bootstrap upgrade` regenerates it in place
    and drops the wake-preflight step (happened live in PR #35; v1.7.1 banks a
    backup under `.substrate/backup/` but the re-apply is manual). This check makes
    the drop loud: red unless the NON-CONTROL lane still runs this wrapper.
    """
    gate = REPO_ROOT / GATE_FILE
    try:
        text = gate.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"gate-wiring: could not read {GATE_FILE}: {exc}", file=sys.stderr)
        return 2
    # Step granularity of the kit-planted gate: each step starts `\n      - `.
    # The wake-preflight step = the wrapper invocation guarded by the
    # non-control-lane condition, in one step block (anchors per PR #18).
    if any(PREFLIGHT_RUN in step and NON_CONTROL_GUARD in step
           for step in text.split("\n      - ")):
        print(f"gate-wiring: OK — {GATE_FILE} non-control lane runs scripts/preflight.py")
        return 0
    print(
        f"gate-wiring: RED — {GATE_FILE} lost the wake-preflight step "
        f"(`{PREFLIGHT_RUN}` guarded by `if: {NON_CONTROL_GUARD}`). The gate file "
        "is KIT-OWNED: a `bootstrap upgrade` regenerated it and dropped the PR #18 "
        "step (as happened live in PR #35). RE-APPLY per the PR #18 recipe — insert "
        "the step between `setup-python` and the session-card gate step (recipe: "
        ".sessions/2026-07-10-gate-ritual-convergence.md § 💡; banked pre-regen "
        "copies live under .substrate/backup/).",
        file=sys.stderr,
    )
    return 1


def _first_line(text: str | None) -> str:
    """First non-empty line of a (possibly multi-line) error, for one-line advisories."""
    for line in (text or "").splitlines():
        if line.strip():
            return line.strip()
    return ""


def check_open_work() -> int:
    """Open-work sweep — ADVISORY ONLY, unconditionally exit 0 (never gates).

    Lists in-flight sibling work at wake/pre-push time: open remote branches besides
    main, plus uncommitted local state. Report-only by construction (the
    harvest-freshness probe's hermeticity rule, ideas/fleet/
    open-work-preflight-sweep-2026-07-10.md Q4): findings, empty findings, and even a
    dead network all PASS — the value is the listing, the exit code carries nothing.
    Origin: PR #40 card 💡 (each repo builds its own open-work ritual step).
    """
    # Leg 1: open remote branches besides main (git transport only — universal).
    try:
        proc = subprocess.run(
            ["git", "ls-remote", "--heads", "origin"],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=30,
        )
        if proc.returncode != 0:
            raise RuntimeError(_first_line(proc.stderr) or f"exit {proc.returncode}")
        heads = [
            (sha[:9], ref[len("refs/heads/"):])
            for line in proc.stdout.splitlines()
            if line.strip()
            for sha, _, ref in [line.partition("\t")]
            if ref.startswith("refs/heads/") and ref != "refs/heads/main"
        ]
        if heads:
            print(f"open-work: {len(heads)} open remote branch(es) besides main "
                  "(advisory — a sibling may be in flight; merge forward-only, "
                  "never rebase):")
            for sha, name in heads:
                print(f"open-work:   {sha}  {name}")
        else:
            print("open-work: no open remote branches besides main")
    except Exception as exc:  # advisory only — a failed sweep is never a failed gate
        print(f"open-work: could not list remote branches ({_first_line(str(exc))}) "
              "— advisory only, still PASS")

    # Leg 2: uncommitted local state (never relevant in CI's clean checkout; at a
    # wake it flags a sibling's — or a crashed session's — half-done tree).
    try:
        proc = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=30,
        )
        if proc.returncode != 0:
            raise RuntimeError(_first_line(proc.stderr) or f"exit {proc.returncode}")
        dirt = [line for line in proc.stdout.splitlines() if line.strip()]
        if dirt:
            print(f"open-work: {len(dirt)} uncommitted local path(s) (advisory):")
            for line in dirt:
                print(f"open-work:   {line}")
        else:
            print("open-work: working tree clean")
    except Exception as exc:
        print(f"open-work: could not read local git status ({_first_line(str(exc))}) "
              "— advisory only, still PASS")

    print("open-work: OK — advisory sweep complete (report-only, never affects the exit)")
    return 0


# --branch-prefix-drift anchors: the PR-merge subject GitHub writes on merge-commit
# landings ("Merge pull request #N from <owner-or-fork>/<branch>"), the `Head-ref:`
# provenance line the auto-merge enabler stamps into squash commit bodies (squash
# subjects carry no branch name — `gh pr merge --auto --squash --body`, see
# .github/workflows/auto-merge-enabler.yml), the config key the auto-merge enabler
# is generated from, and the recurrence bar that separates a convention (>=2 merged
# branches) from a one-off branch name.
MERGE_SUBJECT_RE = re.compile(r"^Merge pull request #\d+ from [^/\s]+/(\S+)$")
HEAD_REF_BODY_RE = re.compile(r"^Head-ref: (\S+)$", re.MULTILINE)
CONFIG_FILE = "substrate.config.json"
DRIFT_RECURRENCE = 2
MERGE_LOG_LIMIT = 200


def _prefix_pattern(branch: str) -> str:
    """Group key for a merged-branch name, in branch_patterns' own vocabulary.

    First path segment + "/*" (`probe/x` → `probe/*`); a slashless name falls back
    to its first hyphen token + "-*" (`seed-games-…` → `seed-*` — the one real
    slashless convention in this repo's history, which a naive `<seg>/*` key would
    have hidden).
    """
    if "/" in branch:
        return branch.split("/", 1)[0] + "/*"
    return branch.split("-", 1)[0] + "-*"


def check_branch_prefix_drift(config_path: Path | None = None) -> int:
    """Branch-prefix drift tripwire — ADVISORY ONLY, unconditionally exit 0.

    Compares the branch prefixes this repo ACTUALLY merges (parsed from local
    git history — hermetic, no network) against
    `substrate.config.json::automerge.branch_patterns`, and reports any RECURRING
    prefix (>= DRIFT_RECURRENCE merged branches) that matches no configured pattern.
    That mismatch is the exact silent-disarm class PR #55 fixed by hand survey: the
    enabler never arms on an unmatched prefix, nothing goes red, and auto-merge
    quietly stops being structural. Report-only by construction (the open-work
    advisory's hermeticity rule): findings, empty findings, a shallow clone, a
    provenance-less squash window, and an unreadable config all PASS — the value is
    the listing, the exit code carries nothing. TWO branch-name sources: (1)
    `git log --merges` PR-merge subjects ("Merge pull request #N from owner/branch"
    — merge-commit landings only), and (2) `Head-ref: <branch>` provenance lines in
    squash commit bodies, stamped at arm time by the auto-merge enabler (squash
    subjects are `<title> (#N)` with no branch name — the idea file's Q4 blind
    spot, thinned by the provenance line from the PR that shipped it onward; the
    subject leg stays the fallback for the pre-provenance history).

    `config_path` overrides the config location — the planted-violation smoke-test
    seam (point it at a doctored copy; production callers pass nothing).
    """
    cfg = config_path if config_path is not None else REPO_ROOT / CONFIG_FILE
    try:
        patterns = json.loads(cfg.read_text(encoding="utf-8")).get(
            "automerge", {}).get("branch_patterns")
    except Exception as exc:
        print(f"branch-prefix-drift: could not read {cfg.name} "
              f"({_first_line(str(exc))}) — advisory only, still PASS")
        return 0
    if not isinstance(patterns, list) or not all(isinstance(p, str) for p in patterns):
        print("branch-prefix-drift: no automerge.branch_patterns list configured — "
              "nothing to compare (enabler not adopted?); advisory only, still PASS")
        return 0

    try:
        proc = subprocess.run(
            ["git", "log", "--merges", "-n", str(MERGE_LOG_LIMIT), "--pretty=%s"],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=30,
        )
        if proc.returncode != 0:
            raise RuntimeError(_first_line(proc.stderr) or f"exit {proc.returncode}")
        subjects = proc.stdout.splitlines()
    except Exception as exc:  # advisory only — a failed survey is never a failed gate
        print(f"branch-prefix-drift: could not read git merge history "
              f"({_first_line(str(exc))}) — advisory only, still PASS")
        return 0

    branches = [m.group(1) for s in subjects if (m := MERGE_SUBJECT_RE.match(s))]

    # Provenance leg: squash landings are NOT merge commits and their default
    # subject carries no branch name, so read the `Head-ref: <branch>` line the
    # auto-merge enabler stamps into squash commit bodies at arm time. The
    # subject leg above stays the fallback for pre-provenance history (and any
    # future merge-commit landings).
    provenance: list[str] = []
    try:
        proc = subprocess.run(
            ["git", "log", "--no-merges", "-n", str(MERGE_LOG_LIMIT), "--pretty=%b"],
            cwd=REPO_ROOT, capture_output=True, text=True, timeout=30,
        )
        if proc.returncode != 0:
            raise RuntimeError(_first_line(proc.stderr) or f"exit {proc.returncode}")
        provenance = HEAD_REF_BODY_RE.findall(proc.stdout)
    except Exception as exc:  # advisory only — the subject leg already ran
        print(f"branch-prefix-drift: could not read squash-provenance bodies "
              f"({_first_line(str(exc))}) — continuing on merge subjects alone")
    branches += provenance

    if not branches:
        print("branch-prefix-drift: no PR merge subjects or Head-ref provenance "
              "lines in local history (shallow clone or pre-provenance squash "
              "window) — nothing to compare, still PASS")
        return 0

    uncovered: dict[str, list[str]] = {}
    for branch in branches:
        if any(fnmatch.fnmatchcase(branch, pat) for pat in patterns):
            continue
        uncovered.setdefault(_prefix_pattern(branch), []).append(branch)
    drifted = {k: v for k, v in uncovered.items() if len(v) >= DRIFT_RECURRENCE}

    if drifted:
        print(f"branch-prefix-drift: DRIFT (advisory) — {len(drifted)} recurring "
              "merged-branch prefix(es) match NO automerge.branch_patterns entry "
              "(the enabler never arms on these — the PR #55 silent-no-op class; "
              "add the pattern or retire the convention):")
        for prefix, names in sorted(drifted.items(), key=lambda kv: -len(kv[1])):
            sample = ", ".join(names[:3]) + (" …" if len(names) > 3 else "")
            print(f"branch-prefix-drift:   {prefix}  ×{len(names)}  (e.g. {sample})")
    else:
        singles = sum(len(v) for v in uncovered.values())
        print(f"branch-prefix-drift: OK — every recurring merged-branch prefix "
              f"matches a configured pattern ({len(branches)} merged branches "
              f"surveyed ({len(provenance)} via Head-ref provenance), "
              f"{len(patterns)} patterns, {singles} one-off unmatched "
              "branch(es) below the recurrence bar)")
    print("branch-prefix-drift: OK — advisory sweep complete "
          "(report-only, never affects the exit)")
    return 0


# --enabler-anchors anchors: the two HOST customizations living in the KIT-OWNED
# auto-merge enabler (regenerated in place by every adopt/upgrade). The kit's
# carve-out scan is STEP-granular: it names the whole added card-guard step but is
# blind to the `--body` provenance edit INSIDE the kit's own arm step (proven live
# on the v1.9.0 upgrade — only the #86-prescribed manual diff caught it). These are
# the exact byte-needles the re-apply duty must preserve.
ENABLER_FILE = ".github/workflows/auto-merge-enabler.yml"
ENABLER_ANCHORS: list[tuple[str, str]] = [
    ("card-status guard (PR #86 — arm-step `if` gates on the card step's output)",
     "steps.card.outputs.skip == '0'"),
    ("Head-ref squash provenance (PR #62/#64 — `--body` stamps the source branch)",
     '--body "Head-ref: $HEAD_REF"'),
]


def check_enabler_anchors() -> int:
    """Enabler-anchor tripwire — ADVISORY ONLY, unconditionally exit 0 (v1.10.0 hop).

    Asserts BOTH host customizations still live in the kit-owned auto-merge enabler:
    the PR #86 card-status guard (the arm step's `if` consults
    `steps.card.outputs.skip`) and the PR #62-lineage `Head-ref:` squash provenance
    (`--body` on the arm command). Every adopt/upgrade regenerates the enabler and
    drops both (v1.9.0 upgrade: the carve-out scan named the guard STEP but was
    step-blind to the in-step `--body` edit — manual diff was the only catch, and
    manual-diff duties are exactly what tripwires exist to replace, per the
    gate-wiring precedent that has caught its class four upgrades running).
    REPORT-ONLY on first landing (deliberate, this hop's card § advisory-mode
    decision): a brand-new check observes before it blocks — if the needle bytes or
    the scan itself are miscalibrated, an advisory misreport costs one log line, a
    red would jam every PR; promote to gating (return 1) after it survives a real
    upgrade cycle. Findings, empty findings, and an unreadable file all PASS — the
    value is the listing, the exit code carries nothing (the open-work advisory's
    hermeticity rule).
    """
    enabler = REPO_ROOT / ENABLER_FILE
    try:
        text = enabler.read_text(encoding="utf-8")
    except OSError as exc:  # advisory only — a missing enabler is adopt's business
        print(f"enabler-anchors: could not read {ENABLER_FILE} "
              f"({_first_line(str(exc))}) — advisory only, still PASS")
        return 0
    missing = [(label, needle) for label, needle in ENABLER_ANCHORS
               if needle not in text]
    if missing:
        print(f"enabler-anchors: DRIFT (advisory) — {len(missing)} of "
              f"{len(ENABLER_ANCHORS)} host customization anchor(s) MISSING from "
              f"{ENABLER_FILE} (the file is KIT-OWNED: an adopt/upgrade regenerated "
              "it and dropped the host edits — the v1.9.0-upgrade class; RE-APPLY "
              "per the re-apply duty, banked pre-regen copies live under "
              ".substrate/backup/):")
        for label, needle in missing:
            print(f"enabler-anchors:   MISSING {label} — needle `{needle}`")
    else:
        print(f"enabler-anchors: OK — both host customization anchors present in "
              f"{ENABLER_FILE} (card-status guard + Head-ref --body provenance)")
    print("enabler-anchors: OK — advisory sweep complete "
          "(report-only, never affects the exit)")
    return 0


# --step-anchor-drift anchors (PR #36 card 💡): the stem that identifies a
# preflight-run-like line regardless of byte drift (`python scripts/preflight.py`,
# `python3 ./scripts/preflight.py`, …) and the step `if:` line the guard must
# actually live on. Any deliberate gate-step rewording must co-edit the
# PREFLIGHT_RUN/NON_CONTROL_GUARD constants — this advisory is that duty's
# tripwire (stem-match, never exact-match: README § The probe battery).
PREFLIGHT_STEM = "scripts/preflight.py"
STEP_IF_RE = re.compile(r"^\s*if:\s*(.*)$", re.MULTILINE)
RUN_LINE_RE = re.compile(r"^\s*run:.*$", re.MULTILINE)


def check_step_anchor_drift(gate_path: Path | None = None) -> int:
    """Step-anchor drift tripwire — ADVISORY ONLY, unconditionally exit 0.

    The gate-wiring self-check (above) matches the PR #18 anchors as byte
    strings, which leaves two silent drift modes when a gate-step rewording
    forgets the co-edit duty (the PR #36 card 💡):

    - FALSE-red-in-waiting: a preflight-run-like line exists whose bytes no
      longer match PREFLIGHT_RUN (e.g. a re-apply rewords `python3` → `python`).
      The binary check would red the next run with a re-apply pointer, but the
      real fix is the constants co-edit — this advisory names it at the
      rewording PR itself, not one wake later.
    - FALSE-green: the anchored run line survives while the guard bytes move
      OFF the step's actual `if:` condition (e.g. into a comment, or the step
      migrates into the control fast lane) — both byte-needles still present in
      one step block, `check_gate_wiring` stays green, semantics gone.

    Findings, empty findings, and an unreadable gate all PASS — the value is
    the listing, the exit code carries nothing (the open-work advisory's
    hermeticity rule; the gating leg stays `--gate-wiring`, unchanged).
    `gate_path` overrides the gate location — the planted-violation smoke-test
    seam (point it at a doctored copy; production callers pass nothing).
    """
    gate = gate_path if gate_path is not None else REPO_ROOT / GATE_FILE
    try:
        text = gate.read_text(encoding="utf-8")
    except OSError as exc:  # advisory only — the gating leg reports the miss
        print(f"step-anchor-drift: could not read {GATE_FILE} "
              f"({_first_line(str(exc))}) — advisory only, still PASS")
        return 0

    findings: list[str] = []
    steps = text.split("\n      - ")
    for step in steps:
        run_lines = [m.group(0).strip() for m in RUN_LINE_RE.finditer(step)
                     if PREFLIGHT_STEM in m.group(0)]
        if not run_lines and PREFLIGHT_RUN in step:
            run_lines = [PREFLIGHT_RUN]
        if not run_lines:
            continue
        # Leg 1 — byte-anchor drift on the run line (stem hit, anchor miss).
        for line in run_lines:
            if PREFLIGHT_RUN not in line:
                findings.append(
                    f"run line `{line[:70]}` stem-matches {PREFLIGHT_STEM} but does "
                    f"not byte-match the anchor `{PREFLIGHT_RUN}` — the gate-wiring "
                    "self-check will FALSE-red on it; co-edit PREFLIGHT_RUN in "
                    "scripts/preflight.py with the deliberate rewording (PR #36 duty)"
                )
        # Leg 2 — guard-position drift: the anchored run line's step carries the
        # guard bytes, but not on its actual `if:` condition (the false-green
        # class check_gate_wiring cannot see).
        if PREFLIGHT_RUN in step and NON_CONTROL_GUARD in step:
            if_m = STEP_IF_RE.search(step)
            if not if_m or NON_CONTROL_GUARD not in if_m.group(0):
                findings.append(
                    f"the `{PREFLIGHT_RUN}` step contains the guard bytes "
                    f"`{NON_CONTROL_GUARD}` but NOT on its `if:` condition — "
                    "check_gate_wiring would false-green while the step runs "
                    "unguarded; restore the guard to the step's `if:` (and co-edit "
                    "NON_CONTROL_GUARD if the rewording is deliberate)"
                )

    if findings:
        print(f"step-anchor-drift: DRIFT (advisory) — {len(findings)} anchor "
              f"finding(s) in {GATE_FILE}:")
        for f in findings:
            print(f"step-anchor-drift:   {f}")
    else:
        print(f"step-anchor-drift: OK — every preflight-run-like line in "
              f"{GATE_FILE} byte-matches the anchor and the guard sits on the "
              "step's `if:` condition")
    print("step-anchor-drift: OK — advisory sweep complete "
          "(report-only, never affects the exit)")
    return 0


# --heartbeat-keys anchors (PR #59 card 💡): the control/README.md § status.md
# format block's documented top-level field set — the ONLY keys a heartbeat may
# carry (kit-owned grammar, EAP §6.8; session-local signals fold into notes: or
# the phase line, never as undeclared extension keys — decided round 4, fold-in
# over declare). Co-edit this set ONLY when the kit's format block itself
# changes. Heartbeat file list comes from substrate.config.json::heartbeat_files
# (default: control/status.md — the same default the kit's checkers use).
HEARTBEAT_DECLARED_KEYS = (
    "updated", "phase", "health", "kit", "last-shipped", "blockers", "orders",
    "⚑ needs-owner", "notes",
)
HEARTBEAT_KEY_RE = re.compile(r"^([A-Za-z⚑][A-Za-z0-9 _⚑-]{0,30}):\s")
DEFAULT_HEARTBEAT_FILES = ["control/status.md"]


def check_heartbeat_keys(status_path: Path | None = None) -> int:
    """Undeclared-heartbeat-key tripwire — ADVISORY ONLY, unconditionally exit 0.

    Parses each declared heartbeat file's top-level `<key>:` tokens and warns on
    any key outside the control/README format block's documented set. An
    undeclared key folds into `phase` as a continuation in a consumer's parser
    (the PR #49 measured leak) — this surfaces it at WRITE time, in the same
    session that would commit it, instead of one out-of-repo parser run later
    (`routine:` was caught only at round-4's first live enforcement — the leak
    class is always measured one key behind). Advisory by construction: the ⚑
    field-check precedent — grammar nags never red a PR. `status_path` overrides
    the file list — the planted-violation smoke-test seam (production callers
    pass nothing).
    """
    if status_path is not None:
        files = [status_path]
    else:
        heartbeats = DEFAULT_HEARTBEAT_FILES
        try:
            declared = json.loads(
                (REPO_ROOT / CONFIG_FILE).read_text(encoding="utf-8")
            ).get("heartbeat_files")
            if isinstance(declared, list) and declared and all(
                    isinstance(f, str) for f in declared):
                heartbeats = declared
        except Exception as exc:  # advisory — fall back to the kit default list
            print(f"heartbeat-keys: could not read {CONFIG_FILE} "
                  f"({_first_line(str(exc))}) — using the default heartbeat list")
        files = [REPO_ROOT / f for f in heartbeats]

    undeclared: list[str] = []
    for path in files:
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except OSError as exc:  # advisory — the status checker gates missing files
            print(f"heartbeat-keys: could not read {path.name} "
                  f"({_first_line(str(exc))}) — advisory only, still PASS")
            continue
        rel = path.name if status_path is not None else str(
            path.relative_to(REPO_ROOT))
        seen = 0
        for lineno, line in enumerate(lines, 1):
            if line.startswith("#") or not line.strip():
                continue  # the `# <project> · status` title / blank separators
            m = HEARTBEAT_KEY_RE.match(line)
            if not m:
                continue  # a continuation line folds into the field above it
            seen += 1
            key = m.group(1).strip()
            if key not in HEARTBEAT_DECLARED_KEYS:
                undeclared.append(
                    f"{rel}:{lineno}: undeclared top-level key `{key}:` — not in "
                    "the control/README format block; fold it into notes: or the "
                    "phase line (round-4 fold-in-over-declare), or declare it in "
                    "the kit grammar first"
                )
        print(f"heartbeat-keys: {rel} — {seen} top-level key line(s) parsed")

    if undeclared:
        print(f"heartbeat-keys: DRIFT (advisory) — {len(undeclared)} undeclared "
              "heartbeat key(s) (the PR #49/#59 extension-key leak class, caught "
              "at write time):")
        for u in undeclared:
            print(f"heartbeat-keys:   {u}")
    else:
        print("heartbeat-keys: OK — every top-level heartbeat key is in the "
              "documented format-block set")
    print("heartbeat-keys: OK — advisory sweep complete "
          "(report-only, never affects the exit)")
    return 0


def main() -> int:
    worst = 0
    for name, cmd in CHECKS:
        try:
            code = subprocess.run(cmd, cwd=REPO_ROOT).returncode
        except OSError as exc:  # fail loud: a check that cannot run is not a pass
            print(f"preflight: could not run {name}: {exc}", file=sys.stderr)
            code = 2
        verdict = "PASS" if code == 0 else "FAIL"
        print(f"preflight: {verdict} — {name} (exit {code})")
        worst = max(worst, code)
    if worst == 0:
        print(f"preflight: OK — all {len(CHECKS)} checks green")
    else:
        print(f"preflight: FAIL — worst exit {worst}")
    return worst


if __name__ == "__main__":
    if "--gate-wiring" in sys.argv[1:]:
        sys.exit(check_gate_wiring())
    if "--open-work" in sys.argv[1:]:
        sys.exit(check_open_work())
    if "--enabler-anchors" in sys.argv[1:]:
        sys.exit(check_enabler_anchors())
    if "--step-anchor-drift" in sys.argv[1:]:
        args = sys.argv[1:]
        gate = None
        if "--gate-file" in args and args.index("--gate-file") + 1 < len(args):
            gate = Path(args[args.index("--gate-file") + 1])
        sys.exit(check_step_anchor_drift(gate))
    if "--heartbeat-keys" in sys.argv[1:]:
        args = sys.argv[1:]
        status = None
        if "--status-file" in args and args.index("--status-file") + 1 < len(args):
            status = Path(args[args.index("--status-file") + 1])
        sys.exit(check_heartbeat_keys(status))
    if "--branch-prefix-drift" in sys.argv[1:]:
        args = sys.argv[1:]
        cfg = None
        if "--config" in args and args.index("--config") + 1 < len(args):
            cfg = Path(args[args.index("--config") + 1])
        sys.exit(check_branch_prefix_drift(cfg))
    sys.exit(main())
