#!/usr/bin/env python3
"""preflight.py — one-command wake/pre-push preflight wrapper (stdlib only).

Runs the whole preflight ritual in sequence and reports one PASS/FAIL line per
check, exiting with the WORST (max) exit code so a single red check reds the run:

- `check_sections.py`          — partition: sections ↔ fleet-manifest active lanes.
- `check_ideas.py`             — contents: every idea file parses per the README grammar.
- `check_ideas.py --outbox`    — integrity: outbox proposals ↔ sim-ready ideas.
- `bootstrap.py check --strict --status-only` — control gate: the status heartbeat.
- `preflight.py --gate-wiring` — self-check: the substrate-gate workflow still runs
  this wrapper in its non-control lane (the KIT-OWNED gate file is regenerated by
  every `bootstrap upgrade`, which drops the PR #18 step — happened live in PR #35).

Convention source: control/README.md § Per-session ritual + README § Landing
conventions — this collects the (previously discipline-only) multi-command ritual
into one command; each check stays independently runnable. Report-only: it never
edits files. Origin: PR #2 session card 💡 (wake-preflight wiring).

Usage:
    python3 scripts/preflight.py

Exit codes: worst child exit — 0 = all green · 1 = violations · 2 = a check could
not run (missing input / unparseable manifest / crashed child, reported as 2).
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PY = sys.executable or "python3"

# The ritual, in order — ONE edit here per new preflight check (keep in sync with
# control/README.md § Per-session ritual, loudly: a check missing here silently
# falls back to session discipline).
CHECKS: list[tuple[str, list[str]]] = [
    ("check_sections", [PY, "scripts/check_sections.py"]),
    ("check_ideas", [PY, "scripts/check_ideas.py"]),
    ("check_ideas --outbox", [PY, "scripts/check_ideas.py", "--outbox"]),
    ("bootstrap check --strict --status-only",
     [PY, "bootstrap.py", "check", "--strict", "--status-only"]),
    ("gate-wiring self-check",
     [PY, "scripts/preflight.py", "--gate-wiring"]),
]

GATE_FILE = ".github/workflows/substrate-gate.yml"
PREFLIGHT_RUN = "run: python3 scripts/preflight.py"
NON_CONTROL_GUARD = "steps.lane.outputs.control_only != 'true'"


def check_gate_wiring() -> int:
    """Assert the gate↔ritual convergence step (PR #18) is still wired.

    The gate file is KIT-OWNED — every `bootstrap upgrade` regenerates it in place
    and drops the wake-preflight step (happened live in PR #35; v1.7.1 banks a
    backup under `.substrate/backup/` but the re-apply is manual). This check makes
    the drop loud: red unless the NON-CONTROL lane still runs this wrapper.
    """
    gate = REPO_ROOT / GATE_FILE
    try:
        text = gate.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"gate-wiring: could not read {GATE_FILE}: {exc}", file=sys.stderr)
        return 2
    # Step granularity of the kit-planted gate: each step starts `\n      - `.
    # The wake-preflight step = the wrapper invocation guarded by the
    # non-control-lane condition, in one step block (anchors per PR #18).
    if any(PREFLIGHT_RUN in step and NON_CONTROL_GUARD in step
           for step in text.split("\n      - ")):
        print(f"gate-wiring: OK — {GATE_FILE} non-control lane runs scripts/preflight.py")
        return 0
    print(
        f"gate-wiring: RED — {GATE_FILE} lost the wake-preflight step "
        f"(`{PREFLIGHT_RUN}` guarded by `if: {NON_CONTROL_GUARD}`). The gate file "
        "is KIT-OWNED: a `bootstrap upgrade` regenerated it and dropped the PR #18 "
        "step (as happened live in PR #35). RE-APPLY per the PR #18 recipe — insert "
        "the step between `setup-python` and the session-card gate step (recipe: "
        ".sessions/2026-07-10-gate-ritual-convergence.md § 💡; banked pre-regen "
        "copies live under .substrate/backup/).",
        file=sys.stderr,
    )
    return 1


def main() -> int:
    worst = 0
    for name, cmd in CHECKS:
        try:
            code = subprocess.run(cmd, cwd=REPO_ROOT).returncode
        except OSError as exc:  # fail loud: a check that cannot run is not a pass
            print(f"preflight: could not run {name}: {exc}", file=sys.stderr)
            code = 2
        verdict = "PASS" if code == 0 else "FAIL"
        print(f"preflight: {verdict} — {name} (exit {code})")
        worst = max(worst, code)
    if worst == 0:
        print(f"preflight: OK — all {len(CHECKS)} checks green")
    else:
        print(f"preflight: FAIL — worst exit {worst}")
    return worst


if __name__ == "__main__":
    if "--gate-wiring" in sys.argv[1:]:
        sys.exit(check_gate_wiring())
    sys.exit(main())
